### ISSUE TITLE
crs and GeoJSON spec

### ISSUE THREAD

**Issue by rafaqz** [visr/GeoJSONTables.jl#13]
I've just written `write` to get this up to spec with GeoJSON.jl.

But in testing, the issue of whether to write `crs` comes up - given the draft GeoJSON standard stating `crs` should not be used, but the test set having `crs` fields.

On top of that, if we have `crs` attached to features in a different format `ArchGDAL` needs to be available for GeoFormatTypes.jl to convert it to json.

@evetion @visr what do you think?

**Comment by evetion** [comment]
According to the spec (it has been an standard for a long time now) [here](https://datatracker.ietf.org/doc/html/rfc7946#section-4), `crs` shouldn't be specified at all, as it always should be WGS84.

**Comment by rafaqz** [comment]
Ok I guess we should delete them from the test data then. Not sure how much we should support legacy files or add warnings?

**Comment by visr** [comment]
We should indeed default to the spec. Note that GDAL still defaults to GeoJSON2008 however, so files with a crs will probably still be common. It would be nice if we can still read those as well. We could error if crs is not epsg:4326, unless the user specifies a ignore_crs keyword or something like that?

**Comment by visr** [comment]
Right now any GeoJSONObject has EPSG:4326 implicitly set as per the spec and https://github.com/visr/GeoJSONTables.jl/blob/d16736d183ebc9eafda85a7d1ae6a4bf97cb7f2d/src/geointerface.jl#L83, regardless if another crs is set according to the GeoJSON2008 spec.
