### ISSUE TITLE
Handling miscellaneous data in geojson

### ISSUE THREAD

**Issue by Sov-trotter** [visr/GeoJSONTables.jl#4]
For now GeoJSONTables can only read properties and geometries while other info viz. crs, bbox etc. is left out. It'd be nice to have some lower level functions to give users the option to do anything with it.

**Comment by Sov-trotter** [comment]
https://github.com/visr/GeoJSONTables.jl/blame/3a8d8f7ce5508be82214690855cbb75749bdb87b/README.md#L51

**Comment by Sov-trotter** [comment]
It'd be nice to close all three issues together.

**Comment by visr** [comment]
Since we just put JSON3.Object in our GeoJSONObject, all extra data is preserved in the object.
