### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by Sov-trotter** [visr/GeoJSONTables.jl#6]
It is necessary to handle the cases where properties appear in one feature, but not other. What can be a possible work around for that case. Fill it up with `missing`?

**Comment by visr** [comment]
Yeah in case we load a GeoJSON in a tabular structure, we should fill it up with `missing`. [This method](https://github.com/visr/GeoJSONTables.jl/blob/c011421b5c0e2e2b1141a6fd6b0cc5bfc85d0126/src/GeoJSONTables.jl#L51-L62) intends to help there, but it may need some revisiting and testing.

**Comment by Sov-trotter** [comment]
Ah, yeah. BTW this has also lead me to wonder, what if the `properties` field is absent altogether? I looked into the GeoJSON specification but found no reference of it. Is it possible for the geojson to give only geometry and the property field being absent? 
Because in that case we will get an error, but if something like `"properties": {}` is present for all the features then it is fine I guess.

**Comment by visr** [comment]
The way I read it in https://tools.ietf.org/html/rfc7946#section-3.2:

> A Feature object has a member with the name "properties".  The
      value of the properties member is an object (any JSON object or a
      JSON null value).

Seems like each Feature must always have a properties member. It can also be null though, so that should be supported as well.

**Comment by Sov-trotter** [comment]
Yeah that makes sense. 
So what can we do here, do we fillup the entire FeatureCollection with `missing` or just an empty NamedTuple is a better idea?
The former method keeps us consistent with the "only a few Features' properties missing" case, while the latter might need an loop to go through all the property fields.

**Comment by visr** [comment]
When we load a FeatureCollection into a tabular form, we should make sure that the union of all field names is taken as the columns. We could do a pass over the data to determine this, not sure if there are better ways. We'll probably store each column in an array, so the missing entries in those columns should indeed be set to missing.

**Comment by Sov-trotter** [comment]
So is it good to have an entire column filled up with missing or just omit it altogether?

**Comment by visr** [comment]
It's fine to have a column entirely filled with missing. If you have a CSV file with

```
A,B,C
1,,3
4,,6
```

You wouldn't want to delete column B because it has only missing data right?

**Comment by Sov-trotter** [comment]
Yeah that's valid, I think same goes for geometries too?
Though it's rare for all the geometries to be missing but we can handle it?

**Comment by visr** [comment]
Yeah we should be able to handle it, the spec says:

>    A Feature object has a member with the name "geometry".  The value
      of the geometry member SHALL be either a Geometry object as
      defined above or, in the case that the Feature is unlocated, a
      JSON null value.

**Comment by Sov-trotter** [comment]
#3

**Comment by visr** [comment]
Right now properties with a `null` JSON value are set to `missing` when using the Tables interface. We don't yet handle the case where some fields just don't appear in some features, but could probably add support for this later, see https://github.com/visr/GeoJSONTables.jl/blob/d16736d183ebc9eafda85a7d1ae6a4bf97cb7f2d/test/runtests.jl#L228-L248. Not sure yet how common this is, GDAL for instance just adds the fields with a `null` value.
