### ISSUE TITLE
Bug in Polygon construction

### ISSUE THREAD

**Issue by Sov-trotter** [visr/GeoJSONTables.jl#7]
So we manually give exterior and interiors to the `Polygon` method [here](https://github.com/visr/GeoJSONTables.jl/blob/meta/src/geometry_basics.jl#L36-L49). 

We calculate `nring` and if `nring == 1`  there's only an exterior. But if `nring>1` , it implies that we have interiors too. So we create an array of interiors.

`Technically if we have nring = 3, it implies that we have one exterior and 2 interiors. `

The bug here is https://github.com/visr/GeoJSONTables.jl/blob/meta/src/geometry_basics.jl#L43 where we are allocating `nring` array size for interiors whereas it should be `nring-1`.

This leaves an extra `#undef` in the interiors array which makes it's way into the final GeometryBasics `Polygon`.

**Comment by Sov-trotter** [comment]
I tried it for `ne_10m_land.geojson` example. 
```julia
using GeometryBasics; const GB = GeometryBasics
using GeoJSONTables, JSON3

jsonbytes = read("ne_10m_land.geojson")

j = JSON3.read(jsonbytes)

geom = j.features[1].geometry.coordinates[90]

GeoJSONTables.geometry(MultiPolygon, geom)

poly = GeoJSONTables.geometry(MultiPolygon, geom)[2]

poly.interiors
2388-element Array{LineString{2,Float64,Point{2,Float64},Base.ReinterpretArray{GeometryBasics.Ngon{2,Float64,2,Point{2,Float64}},1,Tuple{Point{2,Float64},Point{2,Float64}},TupleView{Tuple{Point{2,Float64},Point{2,Float64}},2,1,Array{Point{2,Float64},1}}}},1}:
    [Line([50.922862, 50.922862] => [47.02497, 47.02497])]
    [Line([50.905447, 50.905447] => [47.018948, 47.018948])]
    [Line([50.890798, 50.890798] => [47.022284, 47.022284])]
    [Line([50.868337, 50.868337] => [47.03677, 47.03677])]
    [Line([50.857432, 50.857432] => [47.040025, 47.040025])]
    [Line([50.846528, 50.846528] => [47.03677, 47.03677])]
   ⋮
    [Line([51.141856, 51.141856] => [47.094672, 47.094672])]
    [Line([51.102712, 51.102712] => [47.080471, 47.080471])]
    [Line([50.970714, 50.970714] => [47.059882, 47.059882])]
    [Line([50.951915, 50.951915] => [47.052191, 47.052191])]
 #undef
```

**Comment by visr** [comment]
Yes, nice catch! Indeed needs to be `nring - 1`.

**Comment by Sov-trotter** [comment]
Ah cool. I'll push the changes then. :)

**Comment by visr** [comment]
This no longer applies with the current design.
